### ISSUE TITLE
rename ibus/ibus-homepage to ibus/ibus.github.io

### ISSUE THREAD

**Issue by kidwm** [fujiwarat/ibus.github.io#1]
see github pages
https://pages.github.com/

**Comment by fujiwarat** [comment]
Thanks for that help.

**Comment by fujiwarat** [comment]
Probably I think ibus/ibus.github.io no longer work.
From https://help.github.com/pages
Only "Automatic Page Generator" works.

**Comment by kidwm** [comment]
@fujiwarat go to https://github.com/ibus/ibus.github.io/settings

and check the GitHub Pages section

**Comment by fujiwarat** [comment]
It shows "Your site is ready to be published at http://ibus.github.io."
But I cannot access http://ibus.github.io/docs/ibus-1.5/

![ibus github io](https://cloud.githubusercontent.com/assets/105929/7982487/794bfad4-0af2-11e5-92e7-dd585a38d3e9.png)

**Comment by kidwm** [comment]
Try to add an `index.html` to the top level of the repo, after you renamed the repo, you have to add new commit to trigger the site building process.

**Comment by kidwm** [comment]
@fujiwarat now it works. http://ibus.github.io/docs/ibus-1.5/

**Comment by fujiwarat** [comment]
OK, thanks.
